config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'clients#index'

  resources :clients, only: [:index, :create, :new, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :monthly_revenue, presence: true
  validates :asset_value, presence: true
  validates :due_date, presence: true

  validates :asset_value, numericality: { greater_than_or_equal_to: 500, message: "O valor do título deve ser de pelo menos R$ 500" }

  validates :due_date, :timeliness => {:on_or_after => lambda { Date.current + 10.days }, :type => :date}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create]
  before_action :set_client, only: [:show]

  def create
    @client = Client.new(client_params)
    if @client.valid?
      @client.save!
      redirect_to client_path(@client)
    else
      render :index
    end
  end

  def index
    @client = Client.new
  end

  def show

    # Taxa-base dinâmica variando com o faturamento mensal da empresa
    if @client.monthly_revenue >= 100000
      @fee_per_ten_days = 1.5
    else
      @client.monthly_revenue > 50000 ? @fee_per_ten_days = 1.65 : @fee_per_ten_days = 1.8
    end

    @due_date_in_days = (Date.today - @client.due_date).to_i.abs

    @times_to_apply_fee = (@due_date_in_days / 10) + 1

    @total_fee = (@fee_per_ten_days * @times_to_apply_fee).round(2)

    @asset_with_descount = (@client.asset_value * ((100 - @total_fee) / 100)).round(2)
  end


  private

    def client_params
      params.require(:client).permit(:name, :email, :company_name, :monthly_revenue, :asset_value, :due_date)
    end

    def set_client
      @client = Client.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client, url: clients_path do |f| %>

  <%= f.input :name, placeholder: 'Nome', label: false %>
  <%= f.input :email, placeholder: 'Email', label: false %>
  <%= f.input :company_name, placeholder: 'Nome da empresa', label: false %>
  <%= f.input :monthly_revenue, as: :currency, currency: "R$", placeholder: 'Faturamento mensal aproximado', label: false, error: "Por favor, insira seu faturamento mensal médio"  %>

  <%= f.input :asset_value, as: :currency, currency: "R$", placeholder: 'Valor do título (valor mínimo de R$ 500,00)', label: false, error: "O valor do título deve ser acima de R$ 500,00" %>
  <%= f.input :due_date, as: :date, order: [:day, :month, :year],
    label: "Vencimento do Título (Prazo mínimo de 10 dias)", placeholder: "Vencimento do título" %>

  <%= f.button :submit, 'Simular', class: "btn btn-primary btn-block", remote: true %>
<% end %>

app/views/clients/index.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 col-xs-12">
    <h3>Faça sua simulação:</h3>
    <%= render 'form' %>
  </div>
  <div class="col-sm-5 col-xs-12">
    <div id="new_client"></div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="row margin-top-md">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-default show-results">
        <div class="panel-heading">
            <h2 class="panel-title">Resultado: </h2>
        </div>
        <div class="panel-body">
            <div class="well item">
              <h4>Valor total do título: <span>R$ <%= @client.asset_value %></span></h4>
            </div>
            <div class="well item">
              <h4>Prazo do título, em dias: <span><%= @due_date_in_days %></span></h4>
            </div>
            <div class="well item">
              <h4>Taxa final: <span><%= @total_fee %>%</span></h4>
            </div>
            <div class="well item">
              <h4>Valor do título com desconto: <span>R$ <%= @asset_with_descount %></span></h4>
            </div>
        </div>
        <div class="panel-footer text-right">
          <%= link_to "Recalcular", clients_path, class: "btn btn-md btn-primary" %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rapidoo | Simulação</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>